---
name: uaa

releases:
- name: uaa
  version: latest

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 4

instance_groups:
- name: uaa
  instances: 1
  azs: [z1, z2, z3]
  vm_type: default
  stemcell: default
  persistent_disk: 500
  networks:
  - name: default
  jobs:
  - name: uaa_postgres
    release: uaa
    provides:
      postgres: {as: idp_postgres}
    properties:
      postgres:
        address: 127.0.0.1
        port: 5524
        roles:
          - tag: admin
            name: uaaadmin
            password: admin
        databases:
          - tag: uaa
            name: uaadb
            citext: true

  - name: uaa
    release: uaa
    consumes:
      database: {from: idp_postgres}
    properties:
      uaadb:
        databases:
        - name: uaadb
          tag: uaa
        db_scheme: postgresql
        port: 5524
        roles:
        - name: uaaadmin
          password: admin
          tag: admin
      uaa:
        url: https://uaa.service.uaa.internal:8443
        jwt:
          policy:
            active_key_id: key-1
            keys:
              key-1:
                signingKey: ((uaa-key1.private_key))
        sslCertificate: ((uaa_tls.certificate))
        sslPrivateKey: ((uaa_tls.private_key))
        clients:
          admin:
            authorized-grant-types: authorization_code,client_credentials,refresh_token,user_token,password,urn:ietf:params:oauth:grant-type:saml2-bearer,implicit
            redirect-uri: https://google.com
            scope: uaa.admin,clients.read,clients.write,clients.secret,scim.read,scim.write,clients.admin,uaa.user
            authorities: uaa.admin,clients.admin
            secret: adminsecret
        scim:
          user:
            override: true
          users:
            - name: admin
              password: PASSWORD
              groups:
                - uaa.admin
            - name: marissa
              password: koala
              groups:
                - uaa.user
        #login:
        #  client_secret: PASSWORD
      login:
        protocol: https
        saml:
          activeKeyId: key1
          keys:
            key1:
              key: ((saml-key1.private_key))
              passphrase: ''
              certificate: ((saml-key1.certificate))


variables:
  - name: uaa-key1
    type: rsa
  - name: uaa_ca
    type: certificate
    options:
      is_ca: true
      common_name: uaa
      alternative_names: ["*.uaa.service.uaa.internal"]
      extended_key_usage:
      - server_auth
  - name: saml-key1
    type: certificate
    options:
      ca: uaa_ca
  - name: uaa_tls
    type: certificate
    options:
      ca: uaa_ca
      common_name: uaa.service.uaa.internal

releases:
- name: uaa
  url: https://bosh.io/d/github.com/cloudfoundry/uaa-release
  version: latest


stemcells:
- alias: default
  os: ubuntu-trusty
  version: "latest"
